In [1]:
import pandas as pd
df=pd.read_csv('walmart_clean_data.csv')

In [ ]:
df

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7,5/1/2019,13:08:00,Ewallet,9.1,0.48
1,2,WALM048,Harlingen,Electronic accessories,15.28,5,8/3/2019,10:29:00,Cash,9.6,0.48
2,3,WALM067,Haltom City,Home and lifestyle,46.33,7,3/3/2019,13:23:00,Credit card,7.4,0.33
3,4,WALM064,Bedford,Health and beauty,58.22,8,27/01/19,20:33:00,Ewallet,8.4,0.33
4,5,WALM013,Irving,Sports and travel,86.31,7,8/2/2019,10:37:00,Ewallet,5.3,0.48
...,...,...,...,...,...,...,...,...,...,...,...
9964,9996,WALM056,Rowlett,Fashion accessories,37.00,3,3/8/2023,10:10:00,Cash,3.0,0.33
9965,9997,WALM030,Richardson,Home and lifestyle,58.00,2,22/02/21,14:20:00,Cash,7.0,0.48
9966,9998,WALM050,Victoria,Fashion accessories,52.00,3,15/06/23,16:00:00,Credit card,4.0,0.48
9967,9999,WALM032,Tyler,Home and lifestyle,79.00,2,25/02/21,12:25:00,Cash,7.0,0.48
9968,10000,WALM069,Rockwall,Fashion accessories,62.00,3,26/09/20,9:48:00,Cash,3.0,0.33

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df['Total']=df['unit_price']*df['quantity'].round()

Business Problems
--Q.1 Find different payment method and number of transactions, number of qty sold

In [ ]:
df2=df.groupby('payment_method')['quantity'].agg(['count','sum']).reset_index()
df2.rename(columns={'count':'count_of_trax','sum':'sum_of_quantity'})

  payment_method  count_of_trax  sum_of_quantity
0           Cash           1832             4984
1    Credit card           4256             9567
2        Ewallet           3881             8932

Project Question #2
-- Identify the highest-rated category in each branch, displaying the branch, category
-- AVG RATING

In [3]:
df3=df.groupby(['branch','category'])['rating'].max().reset_index()
# df3.groupby('branch')['rating'].idxmax() gives the series of index labels
df.loc[df3.groupby('branch')['rating'].idxmax()]

,invoice_id,branch,city,category,unit_price,quantity,date,time,payment_method,rating,profit_margin
0,1,WALM003,San Antonio,Health and beauty,74.69,7,5/1/2019,13:08:00,Ewallet,9.1,0.48
5,6,WALM026,Denton,Electronic accessories,85.39,7,25/03/19,18:30:00,Ewallet,4.1,0.48
9,10,WALM065,Texas City,Food and beverages,54.84,3,20/02/19,13:27:00,Credit card,5.9,0.33
17,18,WALM061,Cedar Park,Sports and travel,72.61,6,1/1/2019,10:39:00,Credit card,6.9,0.33
20,21,WALM044,Pharr,Electronic accessories,86.04,5,25/02/19,11:24:00,Ewallet,4.8,0.48
...,...,...,...,...,...,...,...,...,...,...,...
500,501,WALM087,Waxahachie,Sports and travel,73.97,1,3/2/2019,15:53:00,Credit card,5.4,0.33
504,505,WALM048,Harlingen,Sports and travel,88.45,1,25/02/19,16:36:00,Credit card,9.5,0.48
510,511,WALM057,Euless,Sports and travel,90.74,7,16/01/19,18:03:00,Credit card,6.2,0.33
515,516,WALM025,Waco,Fashion accessories,51.47,1,18/03/19,15:52:00,Ewallet,8.5,0.48
518,519,WALM008,Corpus Christi,Home and lifestyle,34.73,2,1/3/2019,18:14:00,Ewallet,9.7,0.48

Q.3 Identify the busiest day for each branch based on the number of transactions

In [22]:
# df['date']=pd.to_datetime(df['date'],format='mixed')
# df['date'].dt.day_name()
df3=df.groupby(['branch',df['date'].dt.day_name()])['invoice_id'].count().reset_index()
df3.loc[df3.groupby('branch')['invoice_id'].idxmax()]

      branch      date  invoice_id
2    WALM001  Saturday          14
10   WALM002    Sunday          15
17   WALM003    Sunday          29
24   WALM004    Sunday          14
29   WALM005    Monday          16
..       ...       ...         ...
670  WALM096   Tuesday          15
672  WALM097    Friday          14
680  WALM098    Monday          14
689  WALM099    Sunday          33
697  WALM100  Thursday          12

[100 rows x 3 columns]

Q. 4
-- Calculate the total quantity of items sold per payment method. List payment_method and total_quantity.

In [23]:
df.groupby('payment_method')['quantity'].sum().reset_index()

  payment_method  quantity
0           Cash      4984
1    Credit card      9567
2        Ewallet      8932

Q.5
-- Determine the average, minimum, and maximum rating of category for each city.
-- List the city, average_rating, min_rating, and max_rating.

In [25]:
df.groupby('city')['rating'].agg(['max','min','mean']).reset_index()

           city   max  min      mean
0       Abilene   9.7  4.0  6.336111
1         Alamo  10.0  3.0  6.595588
2         Alice   9.2  3.0  6.164179
3         Allen   9.0  3.0  6.389041
4      Amarillo   9.0  3.0  6.542308
..          ...   ...  ...       ...
93     Victoria   9.5  3.0  5.119205
94         Waco   9.3  3.0  5.385000
95   Waxahachie   9.5  3.0  5.215079
96  Weatherford   9.0  3.0  5.084242
97      Weslaco   9.8  3.0  5.180808

[98 rows x 4 columns]

Q.6
Calculate the total profit for each category by considering total_profit.
List category and total_profit, ordered from highest to lowest profit.

In [30]:
df['Total_profit']=df['profit_margin']*df['quantity']*df['unit_price']


df.groupby('category')['Total_profit'].sum().reset_index().sort_values(by='Total_profit',ascending=False).round()

                 category  Total_profit
1     Fashion accessories      192315.0
4      Home and lifestyle      192214.0
0  Electronic accessories       30772.0
2      Food and beverages       21553.0
5       Sports and travel       20614.0
3       Health and beauty       18672.0

Q.7
-- Determine the most common payment method for each Branch. Display Branch and the preferred_payment_method.

In [ ]:
df2=df.groupby(['branch','payment_method'])['payment_method'].count().reset_index(name='count')

In [ ]:
df2

In [ ]:
df2.groupby('branch')['count'].idxmax()

In [ ]:
df2.loc[df2.groupby('branch')['count'].idxmax()]

In [ ]:
import plotly.express as px

In [ ]:
df3=df2.groupby('payment_method',as_index=False)['count'].sum()

In [ ]:
px.pie(df3,'payment_method','count')

8.Categorize sales into 3 group MORNING, AFTERNOON, EVENING
Find out each of the shift and number of invoices

In [ ]:
df.drop('mean1',axis=1,inplace=True)

In [ ]:
df.rename(columns=  {'Total':'revenue'},inplace=True)

In [ ]:
# df['time']=pd.to_datetime(df['time'])
df.time.dtype

dtype('<M8[ns]')

In [ ]:


def timing_zone2(t):
  hours = t.hour
  if hours < 12:
    return 'morning'
  elif 12 <= hours < 18:
    return 'afternoon'
  else:
    return 'night'

In [ ]:
df['time_zone']=df['time'].apply(timing_zone2)

In [ ]:
df.groupby('time_zone')['invoice_id'].count().reset_index(name='count_of_invoice')

   time_zone  count_of_invoice
0  afternoon              4636
1    morning              2087
2      night              3246

9. Identify 5 branch with highest decrese ratio in
-- revevenue compare to last year(current year 2023 and last year 2022)
-- rdr == last_rev-cr_rev/ls_rev*100

In [ ]:
df['date']=pd.to_datetime(df['date'],format='mixed')
df['year']=df['date'].dt.year

In [ ]:
df2=df.groupby(['branch','year'])['revenue'].sum().reset_index(name='revenue_sum')

In [ ]:
df_2022=df2[df2.year.isin([2022])]

In [ ]:
df_2023=df2[df2.year.isin([2023])]

In [ ]:
df3=pd.merge(df_2022,df_2023,on='branch',how='inner')

In [ ]:
df3['ratio']=(df3['revenue_sum_x']-df3['revenue_sum_y'])/df3['revenue_sum_x']*100

In [ ]:
df3[['branch','ratio']].sort_values(by='ratio',ascending=False).head(5)

     branch      ratio
44  WALM045  62.622761
46  WALM047  58.581945
97  WALM098  57.890433
32  WALM033  55.645545
80  WALM081  50.667441

In [ ]:
#good but unstacking other way would be more usefull

df_new=df.groupby(['branch',df['date'].dt.year])['revenue'].sum().unstack()

In [ ]:
df_new2=df.groupby([df['date'].dt.year,'branch'])['revenue'].sum().unstack()

In [ ]:
df_new2

branch,WALM001,WALM002,WALM003,WALM004,WALM005,WALM006,WALM007,WALM008,WALM009,WALM010,...,WALM091,WALM092,WALM093,WALM094,WALM095,WALM096,WALM097,WALM098,WALM099,WALM100
date,,,,,,,,,,,,,,,,,,,,,
2019,3671.68,2161.12,6773.56,1885.65,4577.64,1415.46,2459.41,2899.93,3413.34,2247.62,...,2255.55,1477.9,3082.01,1929.35,6323.65,3425.17,2239.91,3340.93,2519.6,3156.34
2020,1814.00,937.00,4822.00,1814.00,1683.00,1882.00,979.00,1510.00,4909.00,1498.00,...,2303.00,213.0,622.00,1575.00,1495.00,1606.00,1460.00,1057.00,3283.0,1604.00
2021,1789.00,1895.00,4178.00,1571.00,1248.00,1811.00,1418.00,1737.00,6557.00,1568.00,...,1228.00,1192.0,1792.00,1081.00,2255.00,1682.00,1417.00,1636.00,3898.0,772.00
2022,1488.00,1169.00,4436.00,1337.00,1994.00,765.00,1301.00,1141.00,4876.00,808.00,...,962.00,1130.0,1640.00,1623.00,1725.00,2288.00,1446.00,2446.00,4662.0,1156.00
2023,1463.00,1572.00,4741.00,958.00,2152.00,2088.00,2547.00,2445.00,5933.00,2114.00,...,2394.00,1026.0,1263.00,1323.00,1699.00,2255.00,814.00,1030.00,3712.0,1566.00

In [ ]:
decrease_ratio=(df_new2.loc[2022]-df_new2.loc[2023])/df_new2.loc[2022]*100

In [ ]:
decrease_ratio.sort_values(ascending=False).head(5).reset_index(name='dec_ratio')

    branch  dec_ratio
0  WALM045  62.622761
1  WALM047  58.581945
2  WALM098  57.890433
3  WALM033  55.645545
4  WALM081  50.667441